apiVersion: v1
kind: ServiceAccount
metadata:
  name: calibre-controller-manager
  namespace: calibre-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: calibre-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - get
  - list
  - watch
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs/status
  verbs:
  - get
  - patch
  - update
# Used to display PhaseChange events in CalibreJobs
# Only required for this Calibre RBAC PoC
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: calibre-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: calibre-manager-role
subjects:
- kind: ServiceAccount
  name: calibre-controller-manager
  namespace: calibre-system
