apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calibre:view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calibre:edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: calibre:admin
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
rules:
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - calibre.siemens.com
  resources:
  - calibrejobs/status
  verbs:
  - get
